version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      # Download and cache dependencies
      #
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install npm dependencies
          command: |
            npm install --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Unit Tests
      - run:
          name: Run unit tests
          command: |
            npm run test
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

workflows:
  build_test:
    jobs:
      - run_tests
